#ifndef SWM_CONSTANTS_H
#define SWM_CONSTANTS_H

#define MAX_CLIENT_NAME_LEN 256
#define MAX_STATUS_BAR_TEXT_LEN 256
#define MAX_COLOR_SCHEMES 2
#define MAX_COLOR_VARIANTS 3
#define MAX_TAGS 9
#define MAX_SUPPORTED_TAGS 31 // Cannot exceed this
#define MAX_TAG_SETS 3
#define MAX_WINDOW_RULES 20
#define MAX_LAYOUTS 3
#define MAX_KEY_BINDINGS 100
#define MAX_BUTTON_BINDINGS 20
#define MAX_LAYOUT_SYMBOL_LEN 16

#endif // SLACKER_CONSTANTS_H
